#!/bin/sh

echo "2018-12-09";

Node most_active_cookie.js cookie_log_test.csv -d 2018-12-09;

echo "\n2018-12-08";

Node most_active_cookie.js cookie_log_test.csv -d 2018-12-08;

echo "\n2018-12-07";

Node most_active_cookie.js cookie_log_test.csv -d 2018-12-07;

echo "\n2018-10-07";

Node most_active_cookie.js cookie_log_test.csv -d 2018-10-07;

